# Generated by Django 4.1.1 on 2022-11-11 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('text', models.TextField(max_length=100)),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Согласен с правилами')),
                ('file', models.FileField(blank=True, null=True, upload_to='form_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='form_imgs/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
