# Generated by Django 4.1.4 on 2023-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORM_MSG', '0003_alter_message_text_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_comment'),
        ),
    ]
