# Generated by Django 4.1.4 on 2023-02-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FORM_MSG', '0004_comment_unique_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment',
        ),
    ]
