# Generated by Django 4.1.1 on 2023-02-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FORM_MSG', '0005_remove_comment_unique_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Messages'},
        ),
    ]
