version: '3.8'

services:
  web:
    build: .
    command: gunicorn django1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8081:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_1
    ports:
      - 5430:5432
  nginx:
    build: infra/nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 9001:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: